spring.application.name=storage

# PostgreSQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/filestorage
spring.datasource.username=storage_user
spring.datasource.password=storage_password
spring.jpa.hibernate.ddl-auto=create-drop

# Yüklenecek maksimum dosya boyutlar?
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Dosyalar?n Windows üzerinde kaydedilece?i klasör yolu
file.upload-dir=C:/Users/serha/Desktop/storage-uploads

application.security.jwt.secret-key=dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSFMyNTYgYWxnb3JpdGht
application.security.jwt.expiration=86400000